### ISSUE TITLE
编译出错哦

### ISSUE THREAD

**Issue by youwi** [comcat/miwifi#4]
yu@Ubuntu:~/miwifi$ make
if [ ! -f kernel/linux-2.6.36/.config ]; then \
        cp kernel/linux-2.6.36/arch/arm/configs/xiaomi-r1d-with-nfs_defconfig \
            kernel/linux-2.6.36/.config; \
    fi
Build the kernel modules of Xiaomi R1D
make[1]: 正在进入目录 `/home/yu/miwifi/kernel/linux-2.6.36'
  CHK     include/linux/version.h
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/basic/docproc
  HOSTCC  scripts/basic/hash
  CHK     include/generated/utsrelease.h
scripts/basic/docproc.c: In function ‘docsect’:
scripts/basic/docproc.c:336:10: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
  asprintf(&s, "DOC: %s", line);
          ^
make[2]: “include/generated/mach-types.h”是最新的。
  HOSTCC  scripts/kallsyms
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
/home/yu/miwifi/toolchain/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin/../libexec/gcc/arm-brcm-linux-uclibcgnueabi/4.5.3/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
make[3]: *** [scripts/mod/empty.o] 错误 1
make[3]: *** 正在等待未完成的任务....
make[2]: *** [scripts/mod] 错误 2
make[2]: *** 正在等待未完成的任务....
make[1]: *** [scripts] 错误 2
make[1]:正在离开目录`/home/yu/miwifi/kernel/linux-2.6.36'
make: **\* [modules] 错误 2

libmpc.so.2这个文件看了看好像有的,没找到原因,才发issue

**Comment by 911061873** [comment]
apt-get install libelf-dev

**Comment by 911061873** [comment]
找不到libmpc*  这些文件在lib文件夹里面有，建立一个连接到use/lib就可以了
